[tool.poetry]
name = "moto-bro"
version = "0.1.0"
description = ""
authors = ["Yamemik <kuancarlos@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
